/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllAdmin;
import Model.Gost;
import Model.Soba;
import Model.TipSobe;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author veron
 */
public class PregledGostijuView extends javax.swing.JDialog {

    Object[] options = {"Potvrdi", "Odustani"};

    /**
     * Creates new form PregledGostijuView
     */
    public PregledGostijuView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNoviBrMobitela = new javax.swing.JTextField();
        btnPrikaziSveGoste = new javax.swing.JButton();
        txtNoviOIB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGosti = new javax.swing.JTable();
        btnAžuriraj = new javax.swing.JButton();
        btnOdustaniPregledG = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTraziOib = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNovoImeGosta = new javax.swing.JTextField();
        txtNovoPrezimeGosta = new javax.swing.JTextField();
        btnPretražiGoste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNoviBrMobitela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoviBrMobitelaKeyPressed(evt);
            }
        });

        btnPrikaziSveGoste.setText("Prikaži sve");
        btnPrikaziSveGoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveGosteActionPerformed(evt);
            }
        });

        txtNoviOIB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoviOIBKeyPressed(evt);
            }
        });

        tblGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra","Ime", "Prezime", "OIB", "Kontakt"
            }
        ));
        tblGosti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGostiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGosti);

        btnAžuriraj.setText("Ažuriraj");
        btnAžuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAžurirajActionPerformed(evt);
            }
        });

        btnOdustaniPregledG.setText("Odustani");
        btnOdustaniPregledG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniPregledGActionPerformed(evt);
            }
        });

        jLabel5.setText("Novo ime gosta:");

        jLabel6.setText("Novo prezime gosta:");

        txtTraziOib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTraziOibKeyPressed(evt);
            }
        });

        jLabel7.setText("Novi broj mobitela:");

        jLabel1.setText("Popis gostiju");

        jLabel8.setText("Novi OIB:");

        jLabel2.setText("Pretraži goste po OIB-u");

        jLabel9.setText("Ažuriranje gosta");

        jLabel3.setText("OIB:");

        btnPretražiGoste.setText("Pretraži");
        btnPretražiGoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretražiGosteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(txtTraziOib, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(btnPretražiGoste, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnPrikaziSveGoste)))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoviBrMobitela, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtNovoPrezimeGosta)
                                    .addComponent(btnOdustaniPregledG, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNovoImeGosta)
                                    .addComponent(txtNoviOIB))
                                .addGap(117, 117, 117)
                                .addComponent(btnAžuriraj)))
                        .addContainerGap(147, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretražiGoste)
                    .addComponent(jLabel3)
                    .addComponent(txtTraziOib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziSveGoste))
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNovoImeGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNovoPrezimeGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoviBrMobitela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNoviOIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAžuriraj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnOdustaniPregledG)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretražiGosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretražiGosteActionPerformed
        try {
            if (txtTraziOib.getText().isEmpty() || txtTraziOib.getText().length() != 11) {
                JOptionPane.showMessageDialog(this, "Unesi točan OIB gosta!\nOIB mora sadržavati točno 11 znamenki!", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            String oib = txtTraziOib.getText();
            pretraziGosteOIB(oib);

            txtTraziOib.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPretražiGosteActionPerformed

    private void btnPrikaziSveGosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveGosteActionPerformed
        prikaziGoste();
    }//GEN-LAST:event_btnPrikaziSveGosteActionPerformed

    private void txtTraziOibKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraziOibKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtTraziOib.setEditable(false);
            JOptionPane.showMessageDialog(this, "OIB gosta smije sadržavati samo znamenke!", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            txtTraziOib.setEditable(true);
        }
    }//GEN-LAST:event_txtTraziOibKeyPressed

    private void tblGostiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGostiMouseClicked
        int red = tblGosti.getSelectedRow();
        int sifra = Integer.parseInt(tblGosti.getValueAt(red, 0).toString()) - 1;

        txtNovoImeGosta.setText(tblGosti.getValueAt(red, 1).toString());
        txtNovoPrezimeGosta.setText(tblGosti.getValueAt(red, 2).toString());
        txtNoviOIB.setText(tblGosti.getValueAt(red, 3).toString());
        txtNoviBrMobitela.setText(tblGosti.getValueAt(red, 4).toString());
       
    }//GEN-LAST:event_tblGostiMouseClicked

    private void btnAžurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAžurirajActionPerformed
        if (tblGosti.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali gosta kojeg želite ažurirati!", "Upozorenje!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            if (txtNovoImeGosta.getText().isEmpty() || txtNovoPrezimeGosta.getText().isEmpty() || txtNoviBrMobitela.getText().isEmpty() || txtNoviOIB.getText().isEmpty() ||txtNoviOIB.getText().length()!=11) {
                JOptionPane.showMessageDialog(this, "Nisu uneseni svi podaci!", "Upozorenje!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int n = JOptionPane.showOptionDialog(null, "Želite li ažurirati gosta?", "Potvrda ažuriranja", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, null);
            if (n == 0) {
                int red = tblGosti.getSelectedRow();
                int sifraGosta = Integer.parseInt(tblGosti.getValueAt(red, 0).toString());
                String ime = txtNovoImeGosta.getText();
                String prezime = txtNovoPrezimeGosta.getText();
                String brMoba = txtNoviBrMobitela.getText();
                String oib = txtNoviOIB.getText();

                Gost gost = new Gost();
                gost.setSifra_gosta(sifraGosta);
                gost.setIme_gosta(ime);
                gost.setPrezime_gosta(prezime);
                gost.setBr_mobitela(brMoba);
                gost.setOib_gosta(oib);

                String potvrda = controll.azurirajGosta(gost);
                JOptionPane.showMessageDialog(this, potvrda);

                txtNovoImeGosta.setText("");
                txtNovoPrezimeGosta.setText("");
                txtNoviBrMobitela.setText("");
                txtNoviOIB.setText("");
                prikaziGoste();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Niste unesli sve podatke!", "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAžurirajActionPerformed

    private void txtNoviOIBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoviOIBKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtNoviOIB.setEditable(false);
            JOptionPane.showMessageDialog(this, "OIB gosta smije sadržavati samo znamenke!", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            txtNoviOIB.setEditable(true);
        }
    }//GEN-LAST:event_txtNoviOIBKeyPressed

    private void txtNoviBrMobitelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoviBrMobitelaKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtNoviBrMobitela.setEditable(false);
            JOptionPane.showMessageDialog(this, "Broj mobitela smije sadržavati samo znamenke!", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            txtNoviBrMobitela.setEditable(true);
        }
    }//GEN-LAST:event_txtNoviBrMobitelaKeyPressed

    private void btnOdustaniPregledGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniPregledGActionPerformed
        dispose();
    }//GEN-LAST:event_btnOdustaniPregledGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledGostijuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledGostijuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledGostijuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledGostijuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PregledGostijuView dialog = new PregledGostijuView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAžuriraj;
    private javax.swing.JButton btnOdustaniPregledG;
    private javax.swing.JButton btnPretražiGoste;
    private javax.swing.JButton btnPrikaziSveGoste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGosti;
    private javax.swing.JTextField txtNoviBrMobitela;
    private javax.swing.JTextField txtNoviOIB;
    private javax.swing.JTextField txtNovoImeGosta;
    private javax.swing.JTextField txtNovoPrezimeGosta;
    private javax.swing.JTextField txtTraziOib;
    // End of variables declaration//GEN-END:variables

    private void prikaziGoste() {
        ((DefaultTableModel) tblGosti.getModel()).setNumRows(0);
        List<Gost> lista = controll.dohvatiGoste();
        for (Gost gost : lista) {
            Object[] rowData = {gost.getSifra_gosta(), gost.getIme_gosta(), gost.getPrezime_gosta(),
                gost.getOib_gosta(), gost.getBr_mobitela()};
            ((DefaultTableModel) tblGosti.getModel()).addRow(rowData);
        }
    }

    private void pretraziGosteOIB(String oib) {
        ((DefaultTableModel) tblGosti.getModel()).setNumRows(0);
        List<Gost> lista = controll.pretraziGosteOIB(oib);
        for (Gost gost : lista) {
            Object[] rowData = {gost.getSifra_gosta(), gost.getIme_gosta(), gost.getPrezime_gosta(),
                gost.getOib_gosta(), gost.getBr_mobitela()};
            ((DefaultTableModel) tblGosti.getModel()).addRow(rowData);
        }
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nema gosta s traženim OIB-om!", "Poruka!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    ControllAdmin controll = new ControllAdmin();

}
