/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author veron
 */
public class Rezervacija_soba_APP extends javax.swing.JFrame {

    PrijavaGostaView prijavaGostaView = new PrijavaGostaView(this,true);
    RezervacijaView rezervacijaView = new RezervacijaView(this,true);
    ZaposleniciView zaposleniciView = new ZaposleniciView(this,true);
    SobeView sobeView = new SobeView(this,true);
    PregledGostijuView pregledGostijuView = new PregledGostijuView(this,true);
    PregledRezervacijaView pregledRezervacijaView = new PregledRezervacijaView(this,true);
    TipSobeView tipSobeView = new TipSobeView(this,true);
    
    /**
     * Creates new form Rezervacija_soba_APP
     */
    public Rezervacija_soba_APP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bltPrijavaGosta = new javax.swing.JButton();
        btnRezervacija = new javax.swing.JButton();
        btnTipSobe = new javax.swing.JButton();
        btnSobe = new javax.swing.JButton();
        btnZaposlenici = new javax.swing.JButton();
        btnPregledGostiju = new javax.swing.JButton();
        btnPregledRezervacija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavni izbornik");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(221, 217, 143));

        bltPrijavaGosta.setBackground(new java.awt.Color(51, 51, 51));
        bltPrijavaGosta.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        bltPrijavaGosta.setForeground(new java.awt.Color(255, 255, 255));
        bltPrijavaGosta.setText("Prijava gosta");
        bltPrijavaGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bltPrijavaGostaActionPerformed(evt);
            }
        });

        btnRezervacija.setBackground(new java.awt.Color(51, 51, 51));
        btnRezervacija.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        btnRezervacija.setForeground(new java.awt.Color(255, 255, 255));
        btnRezervacija.setText("Rezervacija");
        btnRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervacijaActionPerformed(evt);
            }
        });

        btnTipSobe.setBackground(new java.awt.Color(102, 102, 102));
        btnTipSobe.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        btnTipSobe.setForeground(new java.awt.Color(255, 255, 255));
        btnTipSobe.setText("Tip soba");
        btnTipSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipSobeActionPerformed(evt);
            }
        });

        btnSobe.setBackground(new java.awt.Color(102, 102, 102));
        btnSobe.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        btnSobe.setForeground(new java.awt.Color(255, 255, 255));
        btnSobe.setText("Sobe");
        btnSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobeActionPerformed(evt);
            }
        });

        btnZaposlenici.setBackground(new java.awt.Color(102, 102, 102));
        btnZaposlenici.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        btnZaposlenici.setForeground(new java.awt.Color(255, 255, 255));
        btnZaposlenici.setText("Zaposlenici");
        btnZaposlenici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaposleniciActionPerformed(evt);
            }
        });

        btnPregledGostiju.setBackground(new java.awt.Color(153, 153, 153));
        btnPregledGostiju.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        btnPregledGostiju.setForeground(new java.awt.Color(255, 255, 255));
        btnPregledGostiju.setText("Pregled gostiju");
        btnPregledGostiju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledGostijuActionPerformed(evt);
            }
        });

        btnPregledRezervacija.setBackground(new java.awt.Color(153, 153, 153));
        btnPregledRezervacija.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        btnPregledRezervacija.setForeground(new java.awt.Color(255, 255, 255));
        btnPregledRezervacija.setText("Pregled rezervacija");
        btnPregledRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledRezervacijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bltPrijavaGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPregledRezervacija, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRezervacija, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaposlenici, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPregledGostiju, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(bltPrijavaGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRezervacija, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTipSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnZaposlenici, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPregledGostiju, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPregledRezervacija, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bltPrijavaGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bltPrijavaGostaActionPerformed
        prijavaGostaView.setVisible(true);
    }//GEN-LAST:event_bltPrijavaGostaActionPerformed

    private void btnZaposleniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaposleniciActionPerformed
        zaposleniciView.setVisible(true);
    }//GEN-LAST:event_btnZaposleniciActionPerformed

    private void btnRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervacijaActionPerformed
        rezervacijaView.setVisible(true);
    }//GEN-LAST:event_btnRezervacijaActionPerformed

    private void btnPregledGostijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledGostijuActionPerformed
        pregledGostijuView.setVisible(true);
    }//GEN-LAST:event_btnPregledGostijuActionPerformed

    private void btnPregledRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledRezervacijaActionPerformed
        pregledRezervacijaView.setVisible(true);
    }//GEN-LAST:event_btnPregledRezervacijaActionPerformed

    private void btnSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobeActionPerformed
        sobeView.setVisible(true);
    }//GEN-LAST:event_btnSobeActionPerformed

    private void btnTipSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipSobeActionPerformed
        tipSobeView.setVisible(true);
    }//GEN-LAST:event_btnTipSobeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rezervacija_soba_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rezervacija_soba_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rezervacija_soba_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rezervacija_soba_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rezervacija_soba_APP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bltPrijavaGosta;
    private javax.swing.JButton btnPregledGostiju;
    private javax.swing.JButton btnPregledRezervacija;
    private javax.swing.JButton btnRezervacija;
    private javax.swing.JButton btnSobe;
    private javax.swing.JButton btnTipSobe;
    private javax.swing.JButton btnZaposlenici;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
