/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllAdmin;
import Model.Gost;
import Model.Soba;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author veron
 */
public class RezervacijaView extends javax.swing.JDialog {

    //dodat uvjet da se nemre dodat dvaput ista soba u rezervaciji
    /**
     * Creates new form RezervacijaView
     */
    public RezervacijaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prikaziGoste();
        novaRezervacija();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPopisSoba = new javax.swing.JTable();
        datOdlaska = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDodajSobu = new javax.swing.JButton();
        txtTraziOIB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnTraziOIB = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRezSobe = new javax.swing.JTable();
        btnPrikaziSveGoste = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSviGosti = new javax.swing.JTable();
        btnRezerviraj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        datDolaska = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSlobodneSobe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setText("Datum odlaska:");

        tblPopisSoba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra","Broj sobe", "Tip sobe", "Pušenje","Ljubimci", "Cijena"
            }
        ));
        jScrollPane2.setViewportView(tblPopisSoba);

        jLabel6.setText("Ukupno:");

        jLabel1.setText("Pretraživanje gostiju po OIBu:");

        btnDodajSobu.setText("Dodaj sobu");

        txtTraziOIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraziOIBActionPerformed(evt);
            }
        });
        txtTraziOIB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTraziOIBKeyPressed(evt);
            }
        });

        jLabel5.setText("Rezervacija");

        btnTraziOIB.setText("Pretraži");
        btnTraziOIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziOIBActionPerformed(evt);
            }
        });

        tblRezSobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra gosta","Ime gosta", "Prezime gosta", "Šifra sobe","Broj sobe", "Cijena sobe"
            }
        ));
        jScrollPane3.setViewportView(tblRezSobe);

        btnPrikaziSveGoste.setText("Prikaži sve goste");
        btnPrikaziSveGoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveGosteActionPerformed(evt);
            }
        });

        tblSviGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra","Ime", "Prezime", "OIB"
            }
        ));
        tblSviGosti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSviGostiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSviGosti);

        btnRezerviraj.setText("Rezerviraj");

        jLabel2.setText("Popis svih gostiju");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Rezervacija");

        jLabel7.setText("Datum dolaska:");

        jLabel4.setText("Popis slobodnih soba");

        btnSlobodneSobe.setText("Prikaži slobodne sobe");
        btnSlobodneSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlobodneSobeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrikaziSveGoste)
                            .addComponent(btnTraziOIB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTraziOIB, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel3)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnRezerviraj))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(datDolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(datOdlaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDodajSobu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSlobodneSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTraziOIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTraziOIB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikaziSveGoste))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(datDolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(datOdlaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSlobodneSobe)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodajSobu)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnRezerviraj)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTraziOIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraziOIBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraziOIBActionPerformed

    private void btnTraziOIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziOIBActionPerformed
        try {
            if (txtTraziOIB.getText().isEmpty() || txtTraziOIB.getText().length() != 11) {
                JOptionPane.showMessageDialog(this, "Unesi točan OIB gosta!\nOIB mora sadržavati točno 11 znamenki!", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            String oib = txtTraziOIB.getText();
            pretraziGosteOIB(oib);

            txtTraziOIB.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTraziOIBActionPerformed

    private void btnPrikaziSveGosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveGosteActionPerformed
        prikaziGoste();
    }//GEN-LAST:event_btnPrikaziSveGosteActionPerformed

    private void txtTraziOIBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraziOIBKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtTraziOIB.setEditable(false);
            JOptionPane.showMessageDialog(this, "OIB gosta smije sadržavati samo znamenke!", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            txtTraziOIB.setEditable(true);
        }
    }//GEN-LAST:event_txtTraziOIBKeyPressed

    private void tblSviGostiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSviGostiMouseClicked

        int red = tblSviGosti.getSelectedRow();
        int sifraGosta = Integer.parseInt(tblSviGosti.getValueAt(red, 0).toString());
        Gost noviGost = new Gost();
        List<Gost> lista = controll.dohvatiGoste();
        for (Gost gost : lista) {
            if (gost.getSifra_gosta() == sifraGosta) {
                noviGost = gost;
                break;
            }
        }
    }//GEN-LAST:event_tblSviGostiMouseClicked

    private void btnSlobodneSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlobodneSobeActionPerformed
        try {
            Calendar datum1 = datDolaska.getSelectedDate();
            Date d1 = datum1.getTime();
            Calendar datum2 = datOdlaska.getSelectedDate();
            Date d2 = datum2.getTime();

            prikaziSlobodneSobe(d1, d2);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSlobodneSobeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RezervacijaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RezervacijaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RezervacijaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RezervacijaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RezervacijaView dialog = new RezervacijaView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajSobu;
    private javax.swing.JButton btnPrikaziSveGoste;
    private javax.swing.JButton btnRezerviraj;
    private javax.swing.JButton btnSlobodneSobe;
    private javax.swing.JButton btnTraziOIB;
    private datechooser.beans.DateChooserCombo datDolaska;
    private datechooser.beans.DateChooserCombo datOdlaska;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPopisSoba;
    private javax.swing.JTable tblRezSobe;
    private javax.swing.JTable tblSviGosti;
    private javax.swing.JTextField txtTraziOIB;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void prikaziGoste() {
        ((DefaultTableModel) tblSviGosti.getModel()).setNumRows(0);
        List<Gost> lista = controll.dohvatiGoste();
        for (Gost gost : lista) {
            Object[] rowData = {gost.getSifra_gosta(), gost.getIme_gosta(), gost.getPrezime_gosta(),
                gost.getOib_gosta()};
            ((DefaultTableModel) tblSviGosti.getModel()).addRow(rowData);
        }
    }

    private void pretraziGosteOIB(String oib) {
        ((DefaultTableModel) tblSviGosti.getModel()).setNumRows(0);
        List<Gost> lista = controll.pretraziGosteOIB(oib);
        for (Gost gost : lista) {
            Object[] rowData = {gost.getSifra_gosta(), gost.getIme_gosta(), gost.getPrezime_gosta(),
                gost.getOib_gosta()};
            ((DefaultTableModel) tblSviGosti.getModel()).addRow(rowData);
        }
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nema gosta s traženim OIB-om!", "Poruka!", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void prikaziSlobodneSobe(Date d1, Date d2) {
        /*
        ((DefaultTableModel) tblPopisSoba.getModel()).setNumRows(0);
        List<Soba> lista = controll.dohvatiSlobodneSobe(d1, d2);
        for (Soba soba : lista) {
            Object[] rowData = {soba.getSifra_sobe(), soba.getBroj_sobe(), soba.getSifra_tipa().getSifra_tipa_sobe(), soba.isDozvoljeno_pusenje(), soba.isDozvoljeni_ljubimci(), soba.getCijena()};
            ((DefaultTableModel) tblPopisSoba.getModel()).addRow(rowData);
        }if(lista.isEmpty())
            JOptionPane.showMessageDialog(this, "Nema soba koje su slobodne u navedenom razdoblju", "Poruka!", JOptionPane.INFORMATION_MESSAGE);
         */
    }

    private void novaRezervacija() {
        controll.kreiranjeNoveRezervacije();
        prikaziGoste();
        txtTraziOIB.setText("");
        osvjeziRezSobe();
    }

    private void osvjeziRezSobe() {
        ((DefaultTableModel) tblRezSobe.getModel()).setNumRows(0);
        prikaziGoste();
    }

    ControllAdmin controll = new ControllAdmin();

}
